### ISSUE TITLE
hidden symbol

### ISSUE THREAD

**Issue by kittimzhe** [Ewenwan/ORB_SLAM2_SSD_Semantic#20]
/usr/bin/ld: ../Examples/RGB-D/rgbd_tum: hidden symbol `__cpu_indicator_init' in /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a(cpuinfo.o) is referenced by DSO
/usr/bin/ld: final link failed: Bad value

cmakelist里面把和图漾相机的注释了，最后一步出现这个问题

**Comment by GeekRoseboy** [comment]
我跟你一样也注释了，最后也出现了这样的错误
![2020-09-13 16-52-43屏幕截图](https://user-images.githubusercontent.com/48018374/93014223-dc424a00-f5e1-11ea-84b8-98a04d38b4ba.png)

**Comment by kittimzhe** [comment]
> 我跟你一样也注释了，最后也出现了这样的错误
> ![2020-09-13 16-52-43屏幕截图](https://user-images.githubusercontent.com/48018374/93014223-dc424a00-f5e1-11ea-84b8-98a04d38b4ba.png)

 百度查询hidden model的原因说是动态链接库引用了不该引用的隐藏符号。我也没Google到具体的解决方案；我看有相似的案例要把隐藏符号的属性改为default，但是libgcc.h这个头文件中也没有找到这个隐藏符号的声明。 另：可否加个微信交流？：lemhalo

**Comment by kittimzhe** [comment]
> /usr/bin/ld: ../Examples/RGB-D/rgbd_tum: hidden symbol `__cpu_indicator_init' in /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a(cpuinfo.o) is referenced by DSO
> /usr/bin/ld: final link failed: Bad value
> 
> cmakelist里面把和图漾相机的注释了，最后一步出现这个问题
