### ISSUE TITLE
编译出现的问题

### ISSUE THREAD

**Issue by JixinGao** [Ewenwan/ORB_SLAM2_SSD_Semantic#26]
编译已经快完成了，但是出现：
CMakeFiles/rgbd_ty.dir/Examples/RGB-D/my_rgbd.cc.o：在函数‘frameHandler(TY_FRAME_DATA*, void*)’中：
my_rgbd.cc:(.text+0x1086)：对‘TYRegisterWorldToColor2’未定义的引用
../lib/libORB_SLAM2_pc.so：对‘ncnn::Extractor::extract(char const*, ncnn::Mat&)’未定义的引用
../lib/libORB_SLAM2_pc.so：对‘ncnn::Net::register_custom_layer(char const*, ncnn::Layer* (*)())’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/rgbd_ty.dir/build.make:361: recipe for target '../Examples/RGB-D/rgbd_ty' failed
make[2]: *** [../Examples/RGB-D/rgbd_ty] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/rgbd_ty.dir/all' failed
make[1]: *** [CMakeFiles/rgbd_ty.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
这样的问题，请问怎么解决
我还尝试把不使用图漾相机的编译，但是后面两个对ncnn的未定义引用还是存在，能请大神帮忙看下吗

**Comment by JixinGao** [comment]
通过ncnn官方示例的方法链接到cmakelists解决了，动态库静态库链接到cmakelists是有可能出现这个问题的

**Comment by WUSHULI-1** [comment]
> 编译已经快完成了，但是出现： CMakeFiles/rgbd_ty.dir/Examples/RGB-D/my_rgbd.cc.o：在函数‘frameHandler(TY_FRAME_DATA*, void*)’中： my_rgbd.cc:(.text+0x1086)：对‘TYRegisterWorldToColor2’未定义的引用 ../lib/libORB_SLAM2_pc.so：对‘ncnn::Extractor::extract(char const*, ncnn::Mat&)’未定义的引用 ../lib/libORB_SLAM2_pc.so：对‘ncnn::Net::register_custom_layer(char const*, ncnn::Layer* (*)())’未定义的引用 collect2: error: ld returned 1 exit status CMakeFiles/rgbd_ty.dir/build.make:361: recipe for target '../Examples/RGB-D/rgbd_ty' failed make[2]: *** [../Examples/RGB-D/rgbd_ty] Error 1 CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/rgbd_ty.dir/all' failed make[1]: *** [CMakeFiles/rgbd_ty.dir/all] Error 2 Makefile:83: recipe for target 'all' failed make: *** [all] Error 2 这样的问题，请问怎么解决 我还尝试把不使用图漾相机的编译，但是后面两个对ncnn的未定义引用还是存在，能请大神帮忙看下吗

你好 请问这个过程具体是怎样操作的呢

**Comment by bufeng-12** [comment]
您好！我已收到你的邮件！谢谢！          ——曾君

**Comment by chen128** [comment]
您好，对‘TYRegisterWorldToColor2’未定义的引用 ../lib/libORB_SLAM2_pc.so：对‘ncnn::Extractor::extract(char const*,  ncnn::Mat&)’未定义的引用，请问如何解决的，目前将函数注释了可以编译通过。



> 通过ncnn官方示例的方法链接到cmakelists解决了，动态库静态库链接到cmakelists是有可能出现这个问题的
