### ISSUE TITLE
论文链接

### ISSUE THREAD

**Issue by RichardHansir** [Ewenwan/ORB_SLAM2_SSD_Semantic#4]
你好，论文的链接能否发一下？

**Comment by Ewenwan** [comment]
你好，论文被接收了，不过还没发表，等发表了我会上传的。

**Comment by RichardHansir** [comment]
好的，谢谢。

**Comment by Vslamer** [comment]
你好，请问论文现在发表了吗，可以发个链接吗

**Comment by Ewenwan** [comment]
由于某些原因，没去参加会议，论文就没有发表，就不上传了，不过我在readme里面已经加了几张描述相关算法的流程图，相关代码里也有较为详细的算法思路注释。

**Comment by heyonghong** [comment]
@Ewenwan 大神你好，对您这个特别感兴趣。请问论文什么时候能发表呀？特别想看
